### ISSUE TITLE
FEAT: Implement chat functions

### ISSUE THREAD

**Issue by world2222** [Beinus/Server#7]
# Description
* Implement chat functions
<br>

# Todo
- [x] Implement Chat class
- [x] Implement ChatRoom class
- [x] Implement WebSocketConfig class
